# Generated by Django 4.1.1 on 2022-09-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical_history',
            name='vital_signs',
        ),
        migrations.AddField(
            model_name='medical_history',
            name='blood_pressure',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='medical_history',
            name='brathing_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='medical_history',
            name='glycemia',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='medical_history',
            name='hearth_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='medical_history',
            name='oximetry',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='medical_history',
            name='temperature',
            field=models.IntegerField(null=True),
        ),
    ]
